public class JenkinsCICD {

    public static void method(){
        System.debug('testing.........');
        System.debug('through Jenkins deployment .........');
System.debug('added new line');
sdkfjdsklfjdskl
slfjdsklfdsjkl
slkfjdslk
System.debug('added new line');
System.debug('sfafdsfdsfs addded newline');
System.debug('sfafdsfdsfs addded newline');
        System.debug('testing.........');
        System.debug('through Jenkins deployment .........');
    }
}
